### ISSUE TITLE
[AmqpOut node] Publish messages with routing key never works through node definition "Routing key" option

### ISSUE THREAD

**Issue by exogenesick** [abreits/node-red-contrib-amqp#3]
In  AmqpOut node publishing messages with specified routing key now works only through ```msg.topic```. Never works with node configuration dialog/definition which is explained here https://github.com/abreits/node-red-contrib-amqp#output-amqp.

It's because of mistake located here: https://github.com/abreits/node-red-contrib-amqp/blob/master/src/nodejs/amqp.ts#L98

Should be:
```javascript
node.topic = n.routingkey;
```
instead of:
```javascript
node.topic = n.topic;
```
When I debug node definition (AmqpOut node ```n``` parameter) it shows me this:
```javascript
{ id: 'bb1c6ed3.44e39',
  type: 'amqp out',
  z: '1dfb0672.e204fa',
  name: 'producer',
  routingkey: 'a.b.c',
  iotype: '3',
  ioname: 'requests',
  server: '6100766a.9eff88',
  x: 586.1817512512207,
  y: 336.9090938568115,
  wires: [] }
```
Above debug object contains ```routingkey``` property which is proper Routing key option of node definition. Property ```topic``` not exists in this object.

Pull request here #2

**Comment by abreits** [comment]
fixed!
