### ISSUE TITLE
On 1.0.2 version .node-red/node_modules/node-red-contrib-amqp/lib/amqp.html does not exist error

### ISSUE THREAD

**Issue by sarpherviz** [abreits/node-red-contrib-amqp#30]
We use Node-RED and when i try to add palette, there is an errror ".node-red/node_modules/node-red-contrib-amqp/lib/amqp.html does not exist". Because of that we couldn't use..

**Comment by faisalthaheem** [comment]
Here's a complete startup log, version 1.0.1 used to work flawlessly

Welcome to Node-RED
===================

29 Nov 17:42:15 - [info] Node-RED version: v1.0.3
29 Nov 17:42:15 - [info] Node.js  version: v8.10.0
29 Nov 17:42:15 - [info] Linux 4.9.140-tegra arm64 LE
29 Nov 17:42:16 - [info] Loading palette nodes
29 Nov 17:42:19 - [warn] Missing node modules:
29 Nov 17:42:19 - [warn]  - node-red-contrib-amqp (1.0.1): amqp in, amqp out, amqp-server
29 Nov 17:42:19 - [info] Removing modules from config
29 Nov 17:42:19 - [info] Settings file  : /home/faisal/.node-red/settings.js
29 Nov 17:42:19 - [info] Context store  : 'default' [module=memory]
29 Nov 17:42:19 - [info] User directory : /home/faisal/.node-red
29 Nov 17:42:19 - [warn] Projects disabled : editorTheme.projects.enabled=false
29 Nov 17:42:19 - [info] Flows file     : /home/faisal/.node-red/flows_faisal-nano.json
29 Nov 17:42:19 - [info] Server now running at http://127.0.0.1:1880/
29 Nov 17:42:19 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

29 Nov 17:42:19 - [info] Waiting for missing types to be registered:
29 Nov 17:42:19 - [info]  - amqp-server
29 Nov 17:42:35 - [info] Installing module: node-red-contrib-amqp, version: 1.0.2
29 Nov 17:42:45 - [info] Installed module: node-red-contrib-amqp
29 Nov 17:42:45 - [info] Added node types:
29 Nov 17:42:54 - [warn] Failed to enable node:
29 Nov 17:42:54 - [warn]  - amqp : Error: Cannot find module '/home/faisal/.node-red/node_modules/node-red-contrib-amqp/lib/amqp.js'

**Comment by emiliobool** [comment]
1.0.2 is just an empty folder with a package.json file, I just installed 1.0.1 for now.

**Comment by amodelbello** [comment]
I think @abreits published this module before building the project so the lib directory does not exist on npm.

As a temporary workaround for anyone experiencing this issue I've run `npx gulp` and attached the output as a zip file here. If you unzip and add the contents to `.node-red/node_modules/node-red-contrib-amqp` it should work.

[lib.zip](https://github.com/abreits/node-red-contrib-amqp/files/3946729/lib.zip)

**Comment by Codelica** [comment]
@abreits could you possibly publish a new 1.0.3 version that's just a proper build?  Right now 1.0.2 isn't directly installable because of this issue, and 1.0.1 isn't usable on Windows/Mac because it's missing this merge. https://github.com/abreits/node-red-contrib-amqp/pull/28   Would be greatly appreciated!

**Comment by deschmih** [comment]
Hi @abreits, hi @Codelica,
the new version 1.0.3 including this bugfix is still not available on npm https://www.npmjs.com/package/node-red-contrib-amqp .  Is it possible to do this timely. It would be a great job if this becomes available at npm and it would make my life much easier ;-).

**Comment by Codelica** [comment]
@deschmih I wish I could!  But it's going to take someone who can build the project and has permissions to publish a new version. Basically @abreits or potentially one of the contributors like @amodelbello may have access?

**Comment by luiznaac** [comment]
Hello everyone! Is there any update on this? It'd be great to use this package
