### ISSUE TITLE
Server configuration as global and not as local

### ISSUE THREAD

**Issue by didebeach** [abreits/node-red-contrib-amqp#5]
Hi, 

Is there a way, that I can save the amqp server configuration global so I just can pickit up on every workflow? 

Current the configuration is saved in the local workspace of the workflow. As I do have a lot of workflows I like to have just one central configuration space where I can easy switch the configuration between integration or production environment.

My wish would be a possibility to save it local (as default as you have it today) and an optional save it global checkbox.

**Comment by abreits** [comment]
You can change where the configuration is saved in the bottom of the configuration node edit window, it defaults to the flow of the node you define it in, but in the bottom of the window you can select 'Global' and save the settings. This is default Node-Red behavior.

**Comment by didebeach** [comment]
Sorry, that's great. I didn't know that. Perfect solution
