### ISSUE TITLE
amqp nodes stuck 'connecting'

### ISSUE THREAD

**Issue by rossigee** [abreits/node-red-contrib-amqp#9]
Set up a fresh NodeRed flow. Add a trigger and an 'amqp-out' node and link them up. Install a fresh RabbitMQ install (localhost port 5672, guest/guest login). Configure 'amqp-out' node. Trigger flow.

Expected result: Either a successful connection, or an error.
Actual result: Node gets stuck at 'connecting'.

**Comment by rossigee** [comment]
From what I can gather, the cause of this is that 'amqplib' uses AMQP protocol 0.9, and the latest versions of RabbitMQ use AMQP protocol 1.0, which is not compatible.

What seems to be  happening is that 'amqplib' is raising a frame size error, but the node isn't passing in a callback to handle it (PR in progress).

```
Unhandled rejection Error: Frame size exceeds frame max
    at parseFrame (/root/.node-red/node_modules/amqplib/lib/frame.js:55:13)
```

**Comment by rossigee** [comment]
OK, seems I was mistaken. It turned out to be a dodgy proxy. However, the PR I've prepared does fix the problem of it getting stuck at 'connecting'.

**Comment by stefanosPap** [comment]
Hey @rossigee ! I have the same issue. Could you explain me how did you solve this?
